# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  binary: '{{ .ProjectName }}_v{{ .Version }}'
release:
  prerelease: auto
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  # Additional files/globs to add to the archive.
  files:
    - LICENSE*
    - README*
    - CHANGELOG*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
